# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .azure_red_hat_open_shift_client import AzureRedHatOpenShiftClient
from .version import VERSION

__all__ = ['AzureRedHatOpenShiftClient']

__version__ = VERSION

