# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .azure_red_hat_open_shift import AzureRedHatOpenShift
from .version import VERSION
from azure.cli.core.profiles import register_resource_type

__all__ = ['AzureRedHatOpenShift']

__version__ = VERSION

